name: Integration

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test, Lint Check Format and Types
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 👀 Checkout Code
        uses: actions/checkout@v4
      - name: 🥟 Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: 🐢 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: 📦 Install Dependencies
        run: bun install
      - name: 📝 Check Code Format
        run: bun run format:check
      - name: 🚨 Lint Code
        run: bun run lint
      - name: ✅ Type Check Code
        run: bun run typecheck
      - name: 🌍 Check Translations
        run: bun run i18n:check
      - name: 🧪 Run Tests
        run: bun test

  build:
    name: Build Site
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: 👀 Checkout Code
        uses: actions/checkout@v4
      - name: 🥟 Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: 🐢 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: 📦 Install Dependencies
        run: bun install
      - name: 🏗️ Build Site
        run: bun run build
